# Generated by Django 3.1 on 2020-09-26 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_bisness'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bisness',
            old_name='user',
            new_name='author',
        ),
    ]
