# Generated by Django 3.1 on 2020-09-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200927_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='company_adress',
        ),
    ]
