# Generated by Django 3.1 on 2020-09-27 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_company_company_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_inn',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
