# Generated by Django 3.1 on 2020-10-03 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200927_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliate_name', models.CharField(max_length=254, unique=True)),
                ('affiliate_adres', models.CharField(max_length=254, unique=True)),
                ('tel_number', models.CharField(max_length=254, unique=True)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.company')),
            ],
        ),
    ]
