# Generated by Django 3.1 on 2020-10-03 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_affiliater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliater',
            name='company_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blog.company'),
        ),
    ]
