# Generated by Django 3.1 on 2020-10-03 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20201003_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliater',
            name='company_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.company'),
        ),
    ]
