# Generated by Django 3.1 on 2020-10-03 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201003_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=254)),
                ('employee_surname', models.CharField(max_length=254)),
                ('employee_patronymic', models.CharField(max_length=254)),
                ('affiliate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.affiliater')),
            ],
        ),
    ]
