# Generated by Django 3.1 on 2020-10-05 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='affiliate_id',
        ),
    ]
