# Generated by Django 3.1 on 2020-10-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_services_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='time',
            field=models.DurationField(default=25),
        ),
    ]
