# Generated by Django 3.1 on 2020-10-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_services_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.DurationField(default=1800000),
        ),
    ]
