# Generated by Django 3.1 on 2020-10-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20201008_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='time',
            field=models.DurationField(),
        ),
    ]
