# Generated by Django 3.1 on 2020-10-08 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20201008_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='time',
        ),
    ]
